### ISSUE TITLE
Healing prediction not functioning

### ISSUE THREAD

**Issue by Hmmintriguing** [caboyd/LunaUnitFrames-ClassicFix#6]
I have healing prediction turned on for both "Player" and "Target", and it does not show the healing prediction for either. 

I had invited people to my group to see if I had to have the person that was healing in my group, but that did not work either. The opacity setting is also maxed out at 1 for both "Player" and "Target", but I still do not see it.

**Comment by caboyd** [comment]
Healing prediction should work on all targets. Make sure you don't have healcomm included in a separate addon because that could cause issues.
![healing pred](https://github.com/caboyd/LunaUI-ClassicFix/assets/10170577/3303c0d1-2b2d-419b-a113-5d6d8cf74159)

**Comment by Hmmintriguing** [comment]
I do not have any sort of Healcomm addon or any unit frame addon that has built-in healing prediction.

It was working for me when I was raiding earlier this week, but it does not seem to work when a random player would heal me, or if someone would heal me when I was in a party.

Is it supposed to function like that, or is there a way to make it so healing prediction would work outside of being in a raid?

**Comment by caboyd** [comment]
The only way for it to work is if both players have an addon that includes healcomm and are both grouped in a party or raid. Unfortunately that is a limitation that can't be changed in classic wow. But, I think you should see healing prediction on targets even if they don't have healcomm though.

**Comment by caboyd** [comment]
This is what is looks like when you heal someone without healcomm. You can only see your own healing predictions.  
![healcomm1](https://github.com/caboyd/LunaUI-ClassicFix/assets/10170577/12443e2e-1a0d-4798-81dc-0c5055fecb7b)  

This is what happens when someone without healcomm heals you or anyone else. You do not see any predictions.  
![healcomm2](https://github.com/caboyd/LunaUI-ClassicFix/assets/10170577/2d8ddc02-c957-4410-bdee-00d1e57b7461)  

If you know the person you can ask them to install an addon like
https://www.curseforge.com/wow/addons/healbarsclassic-hotfix

**Comment by Hmmintriguing** [comment]
Ah okay. Got it. Thank you for the clarification.
